---
- apt:
    name: thrift-compiler
  remote_user: root
  when: ansible_os_family == 'Debian'

- template:
    src: compile-thrift.sh
    dest: '{{ ansible_user_dir }}/compile-thrift.sh'
    mode: 0755

- stat:
    path: '{{ ansible_user_dir }}/opt/thrift-{{ thrift.version }}'
  register: check_thrift

- shell: '{{ ansible_user_dir }}/compile-thrift.sh {{ thrift.version }}'
  when: check_thrift.stat.exists == False

- homebrew:
    name: thrift
  when: ansible_system == 'Darwin'
